# Generated by Django 6.0 on 2025-12-16 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del plano', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional', null=True)),
                ('archivo_pdf', models.FileField(help_text='Archivo PDF del plano', upload_to='uploads/planos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Procesamiento'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('texto_extraido', models.TextField(blank=True, help_text='Texto extraído del PDF', null=True)),
                ('datos_procesados', models.JSONField(blank=True, help_text='Datos estructurados extraídos', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
