# Generated by Django 6.0 on 2025-12-16 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='memoria_path',
            field=models.CharField(blank=True, help_text='Ruta de la memoria Word generada', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos', to=settings.AUTH_USER_MODEL),
        ),
    ]
